//TODO: AUTH TESTING
//TODO: JWT ARE BEING PRODUCED
//TODO: HASHES ARE FUNCTIONING
//TODO: TOKENS ARE BEING RETURNED AND UTILIZIED PROPERLY
//TODO: JWT SHOULD VIA AUTH MIDDLEWARE POPULATE A USER WITH THE PAYLOAD ASSOCIATED WITH VALID JWT